[package]
name = "remus"
version = "0.1.0"
edition = "2021"
authors = ["Brayden Moon <brayden@foxycorps.com>"]
description = "A flexible and efficient network messaging library"
license = "MIT"

[dependencies]
bitflags = "2.6.0"
byteorder = "1.5.0"
bytes = "1.9.0"
futures = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
time = { version = "0.3.36", features = ["std"] }
tokio = { version = "1.41.1", features = ["full"] }
flate2 = "1.0.28"
aes-gcm = "0.10.3"
rand = "0.8.5"
sha2 = "0.10"
zstd = "0.13"
lz4 = "1.24"
tracing = "0.1"
metrics = "0.21"
uuid = { version = "1.7", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4.4"
criterion = "0.5"
proptest = "1.4"
